package com.company;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

public class Main {

    public static void main(String[] args) {

        String text = "forward 2\n" +
                "down 4\n" +
                "down 3\n" +
                "up 4\n" +
                "down 1\n" +
                "down 8\n" +
                "up 9\n" +
                "forward 1\n" +
                "down 9\n" +
                "forward 6\n" +
                "down 7\n" +
                "forward 1\n" +
                "down 1\n" +
                "up 2\n" +
                "forward 8\n" +
                "down 3\n" +
                "down 9\n" +
                "down 3\n" +
                "down 8\n" +
                "forward 3\n" +
                "forward 5\n" +
                "up 8\n" +
                "forward 6\n" +
                "forward 5\n" +
                "forward 6\n" +
                "forward 4\n" +
                "up 3\n" +
                "forward 1\n" +
                "up 4\n" +
                "forward 2\n" +
                "up 2\n" +
                "up 2\n" +
                "down 6\n" +
                "forward 3\n" +
                "forward 4\n" +
                "forward 5\n" +
                "forward 1\n" +
                "down 1\n" +
                "down 1\n" +
                "forward 3\n" +
                "forward 2\n" +
                "up 7\n" +
                "forward 6\n" +
                "down 5\n" +
                "forward 9\n" +
                "up 4\n" +
                "down 6\n" +
                "up 8\n" +
                "forward 7\n" +
                "forward 5\n" +
                "forward 8\n" +
                "down 5\n" +
                "down 9\n" +
                "forward 3\n" +
                "forward 2\n" +
                "forward 9\n" +
                "forward 1\n" +
                "down 3\n" +
                "forward 1\n" +
                "down 9\n" +
                "forward 4\n" +
                "forward 3\n" +
                "forward 7\n" +
                "forward 6\n" +
                "forward 6\n" +
                "forward 6\n" +
                "forward 8\n" +
                "forward 5\n" +
                "forward 4\n" +
                "up 1\n" +
                "forward 8\n" +
                "forward 1\n" +
                "down 7\n" +
                "forward 2\n" +
                "up 9\n" +
                "forward 4\n" +
                "up 7\n" +
                "down 4\n" +
                "down 3\n" +
                "down 9\n" +
                "down 7\n" +
                "down 1\n" +
                "forward 2\n" +
                "up 6\n" +
                "down 2\n" +
                "down 3\n" +
                "down 5\n" +
                "forward 6\n" +
                "forward 5\n" +
                "forward 6\n" +
                "forward 2\n" +
                "forward 1\n" +
                "forward 5\n" +
                "forward 5\n" +
                "down 9\n" +
                "forward 8\n" +
                "forward 3\n" +
                "down 8\n" +
                "up 2\n" +
                "forward 5\n" +
                "forward 6\n" +
                "down 1\n" +
                "down 7\n" +
                "down 5\n" +
                "forward 3\n" +
                "down 9\n" +
                "down 2\n" +
                "forward 6\n" +
                "forward 6\n" +
                "forward 4\n" +
                "up 5\n" +
                "up 2\n" +
                "up 2\n" +
                "up 2\n" +
                "forward 2\n" +
                "up 3\n" +
                "down 4\n" +
                "forward 2\n" +
                "down 6\n" +
                "forward 1\n" +
                "down 8\n" +
                "up 6\n" +
                "up 9\n" +
                "forward 7\n" +
                "forward 5\n" +
                "forward 9\n" +
                "forward 5\n" +
                "up 3\n" +
                "up 6\n" +
                "up 3\n" +
                "forward 9\n" +
                "forward 7\n" +
                "up 7\n" +
                "forward 3\n" +
                "forward 3\n" +
                "down 5\n" +
                "down 2\n" +
                "down 1\n" +
                "down 8\n" +
                "up 7\n" +
                "down 2\n" +
                "up 4\n" +
                "forward 5\n" +
                "down 5\n" +
                "down 8\n" +
                "down 4\n" +
                "down 8\n" +
                "down 4\n" +
                "down 8\n" +
                "down 2\n" +
                "forward 5\n" +
                "down 9\n" +
                "forward 6\n" +
                "forward 5\n" +
                "up 4\n" +
                "up 2\n" +
                "down 7\n" +
                "down 9\n" +
                "forward 6\n" +
                "forward 6\n" +
                "down 3\n" +
                "up 9\n" +
                "up 8\n" +
                "down 4\n" +
                "forward 9\n" +
                "down 7\n" +
                "down 4\n" +
                "down 6\n" +
                "down 4\n" +
                "down 7\n" +
                "down 2\n" +
                "up 9\n" +
                "forward 9\n" +
                "forward 6\n" +
                "down 6\n" +
                "up 6\n" +
                "down 7\n" +
                "down 5\n" +
                "forward 9\n" +
                "down 9\n" +
                "down 8\n" +
                "down 6\n" +
                "down 3\n" +
                "forward 5\n" +
                "down 5\n" +
                "forward 2\n" +
                "up 4\n" +
                "down 5\n" +
                "forward 6\n" +
                "forward 6\n" +
                "forward 6\n" +
                "down 4\n" +
                "down 8\n" +
                "down 3\n" +
                "down 5\n" +
                "forward 6\n" +
                "forward 2\n" +
                "forward 4\n" +
                "forward 2\n" +
                "forward 3\n" +
                "up 9\n" +
                "forward 8\n" +
                "down 5\n" +
                "down 9\n" +
                "forward 5\n" +
                "forward 7\n" +
                "down 5\n" +
                "down 2\n" +
                "up 3\n" +
                "forward 4\n" +
                "forward 4\n" +
                "up 4\n" +
                "forward 5\n" +
                "forward 8\n" +
                "up 4\n" +
                "forward 3\n" +
                "down 8\n" +
                "up 8\n" +
                "forward 9\n" +
                "up 9\n" +
                "forward 5\n" +
                "forward 8\n" +
                "down 8\n" +
                "up 9\n" +
                "up 2\n" +
                "forward 3\n" +
                "forward 7\n" +
                "down 9\n" +
                "down 6\n" +
                "forward 5\n" +
                "down 1\n" +
                "forward 6\n" +
                "forward 8\n" +
                "up 2\n" +
                "down 8\n" +
                "forward 2\n" +
                "forward 7\n" +
                "down 7\n" +
                "down 7\n" +
                "down 7\n" +
                "down 3\n" +
                "up 6\n" +
                "down 5\n" +
                "down 4\n" +
                "forward 1\n" +
                "forward 3\n" +
                "down 3\n" +
                "down 1\n" +
                "forward 7\n" +
                "forward 8\n" +
                "up 8\n" +
                "forward 3\n" +
                "forward 8\n" +
                "up 9\n" +
                "down 5\n" +
                "down 9\n" +
                "forward 4\n" +
                "down 9\n" +
                "up 8\n" +
                "up 1\n" +
                "forward 6\n" +
                "down 2\n" +
                "up 2\n" +
                "down 3\n" +
                "up 1\n" +
                "down 7\n" +
                "down 8\n" +
                "forward 6\n" +
                "forward 8\n" +
                "up 5\n" +
                "up 2\n" +
                "down 1\n" +
                "forward 6\n" +
                "down 1\n" +
                "up 6\n" +
                "down 9\n" +
                "down 8\n" +
                "down 5\n" +
                "down 7\n" +
                "forward 8\n" +
                "down 1\n" +
                "up 5\n" +
                "down 2\n" +
                "down 5\n" +
                "forward 9\n" +
                "up 8\n" +
                "down 6\n" +
                "forward 7\n" +
                "forward 8\n" +
                "down 5\n" +
                "forward 3\n" +
                "forward 4\n" +
                "up 1\n" +
                "forward 2\n" +
                "forward 9\n" +
                "up 7\n" +
                "down 9\n" +
                "forward 2\n" +
                "down 3\n" +
                "down 6\n" +
                "down 9\n" +
                "forward 4\n" +
                "up 3\n" +
                "forward 3\n" +
                "down 6\n" +
                "forward 1\n" +
                "down 3\n" +
                "down 4\n" +
                "down 8\n" +
                "down 5\n" +
                "forward 6\n" +
                "down 7\n" +
                "forward 6\n" +
                "up 8\n" +
                "forward 9\n" +
                "down 3\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 3\n" +
                "forward 9\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 4\n" +
                "down 1\n" +
                "forward 3\n" +
                "forward 3\n" +
                "forward 3\n" +
                "down 1\n" +
                "down 6\n" +
                "up 1\n" +
                "down 6\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 4\n" +
                "down 4\n" +
                "forward 5\n" +
                "down 4\n" +
                "up 4\n" +
                "up 7\n" +
                "down 4\n" +
                "forward 4\n" +
                "down 8\n" +
                "down 5\n" +
                "down 2\n" +
                "down 3\n" +
                "forward 3\n" +
                "down 4\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 2\n" +
                "up 2\n" +
                "down 8\n" +
                "forward 9\n" +
                "down 1\n" +
                "up 1\n" +
                "down 8\n" +
                "down 8\n" +
                "up 2\n" +
                "down 8\n" +
                "up 2\n" +
                "forward 4\n" +
                "down 2\n" +
                "forward 8\n" +
                "down 1\n" +
                "down 9\n" +
                "forward 3\n" +
                "up 5\n" +
                "down 8\n" +
                "down 2\n" +
                "forward 5\n" +
                "forward 1\n" +
                "forward 6\n" +
                "forward 1\n" +
                "down 8\n" +
                "forward 3\n" +
                "down 5\n" +
                "up 7\n" +
                "down 8\n" +
                "forward 5\n" +
                "down 8\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 9\n" +
                "forward 9\n" +
                "down 8\n" +
                "forward 7\n" +
                "forward 1\n" +
                "forward 9\n" +
                "forward 8\n" +
                "forward 2\n" +
                "down 4\n" +
                "forward 8\n" +
                "up 7\n" +
                "down 2\n" +
                "down 6\n" +
                "forward 5\n" +
                "forward 4\n" +
                "down 5\n" +
                "down 2\n" +
                "forward 2\n" +
                "up 8\n" +
                "up 4\n" +
                "down 8\n" +
                "forward 2\n" +
                "up 3\n" +
                "forward 3\n" +
                "down 4\n" +
                "forward 8\n" +
                "forward 7\n" +
                "forward 4\n" +
                "up 1\n" +
                "down 6\n" +
                "forward 1\n" +
                "down 3\n" +
                "forward 6\n" +
                "up 3\n" +
                "forward 7\n" +
                "down 6\n" +
                "forward 7\n" +
                "forward 5\n" +
                "forward 8\n" +
                "down 9\n" +
                "up 7\n" +
                "down 1\n" +
                "down 5\n" +
                "forward 1\n" +
                "down 8\n" +
                "down 1\n" +
                "forward 4\n" +
                "forward 5\n" +
                "forward 5\n" +
                "down 9\n" +
                "forward 9\n" +
                "down 4\n" +
                "forward 1\n" +
                "up 8\n" +
                "down 5\n" +
                "down 9\n" +
                "down 3\n" +
                "down 2\n" +
                "down 5\n" +
                "down 3\n" +
                "forward 7\n" +
                "up 3\n" +
                "forward 3\n" +
                "down 4\n" +
                "up 5\n" +
                "forward 4\n" +
                "up 6\n" +
                "down 4\n" +
                "forward 2\n" +
                "up 3\n" +
                "down 2\n" +
                "up 1\n" +
                "up 7\n" +
                "down 5\n" +
                "up 3\n" +
                "forward 5\n" +
                "up 2\n" +
                "down 9\n" +
                "down 6\n" +
                "forward 5\n" +
                "up 3\n" +
                "down 7\n" +
                "up 1\n" +
                "forward 1\n" +
                "forward 3\n" +
                "down 9\n" +
                "down 1\n" +
                "forward 6\n" +
                "down 5\n" +
                "forward 8\n" +
                "down 1\n" +
                "down 5\n" +
                "up 6\n" +
                "forward 8\n" +
                "forward 8\n" +
                "forward 9\n" +
                "down 1\n" +
                "down 6\n" +
                "down 8\n" +
                "up 1\n" +
                "down 7\n" +
                "forward 3\n" +
                "forward 5\n" +
                "forward 2\n" +
                "down 4\n" +
                "forward 4\n" +
                "forward 2\n" +
                "down 8\n" +
                "up 2\n" +
                "down 1\n" +
                "up 9\n" +
                "down 4\n" +
                "up 9\n" +
                "down 2\n" +
                "forward 5\n" +
                "forward 4\n" +
                "forward 7\n" +
                "down 8\n" +
                "forward 4\n" +
                "down 5\n" +
                "forward 7\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 3\n" +
                "forward 7\n" +
                "forward 8\n" +
                "forward 2\n" +
                "down 3\n" +
                "forward 4\n" +
                "down 6\n" +
                "forward 4\n" +
                "forward 3\n" +
                "down 3\n" +
                "forward 3\n" +
                "down 8\n" +
                "down 2\n" +
                "forward 6\n" +
                "down 4\n" +
                "down 9\n" +
                "down 2\n" +
                "down 7\n" +
                "forward 4\n" +
                "forward 1\n" +
                "forward 7\n" +
                "down 9\n" +
                "down 5\n" +
                "forward 5\n" +
                "up 7\n" +
                "forward 4\n" +
                "down 1\n" +
                "up 3\n" +
                "down 5\n" +
                "down 3\n" +
                "down 7\n" +
                "down 7\n" +
                "down 7\n" +
                "up 6\n" +
                "forward 3\n" +
                "down 6\n" +
                "down 3\n" +
                "up 2\n" +
                "down 7\n" +
                "forward 5\n" +
                "forward 5\n" +
                "down 6\n" +
                "forward 9\n" +
                "up 2\n" +
                "forward 6\n" +
                "forward 3\n" +
                "forward 5\n" +
                "forward 9\n" +
                "forward 1\n" +
                "up 4\n" +
                "up 7\n" +
                "down 8\n" +
                "down 3\n" +
                "forward 1\n" +
                "down 6\n" +
                "up 8\n" +
                "down 7\n" +
                "down 8\n" +
                "down 9\n" +
                "down 9\n" +
                "forward 5\n" +
                "down 6\n" +
                "up 7\n" +
                "down 3\n" +
                "down 5\n" +
                "down 5\n" +
                "down 6\n" +
                "up 3\n" +
                "forward 8\n" +
                "down 4\n" +
                "up 8\n" +
                "forward 4\n" +
                "down 1\n" +
                "up 8\n" +
                "up 5\n" +
                "down 4\n" +
                "up 8\n" +
                "forward 8\n" +
                "forward 7\n" +
                "up 3\n" +
                "down 7\n" +
                "forward 8\n" +
                "down 1\n" +
                "down 7\n" +
                "down 5\n" +
                "down 5\n" +
                "down 2\n" +
                "up 3\n" +
                "forward 3\n" +
                "forward 8\n" +
                "down 4\n" +
                "down 3\n" +
                "up 7\n" +
                "down 1\n" +
                "down 9\n" +
                "forward 9\n" +
                "forward 1\n" +
                "forward 1\n" +
                "forward 2\n" +
                "down 7\n" +
                "down 9\n" +
                "up 5\n" +
                "down 1\n" +
                "forward 4\n" +
                "forward 9\n" +
                "forward 3\n" +
                "forward 3\n" +
                "forward 4\n" +
                "forward 1\n" +
                "down 2\n" +
                "down 2\n" +
                "up 1\n" +
                "forward 7\n" +
                "forward 8\n" +
                "forward 6\n" +
                "up 6\n" +
                "down 5\n" +
                "forward 2\n" +
                "down 4\n" +
                "forward 5\n" +
                "forward 2\n" +
                "forward 7\n" +
                "down 1\n" +
                "down 9\n" +
                "forward 2\n" +
                "forward 2\n" +
                "forward 3\n" +
                "up 2\n" +
                "up 2\n" +
                "up 2\n" +
                "down 5\n" +
                "forward 5\n" +
                "forward 9\n" +
                "down 4\n" +
                "down 2\n" +
                "down 5\n" +
                "down 9\n" +
                "up 7\n" +
                "forward 2\n" +
                "forward 7\n" +
                "forward 4\n" +
                "forward 5\n" +
                "down 5\n" +
                "down 8\n" +
                "down 9\n" +
                "down 4\n" +
                "up 8\n" +
                "up 1\n" +
                "forward 8\n" +
                "up 2\n" +
                "up 8\n" +
                "up 4\n" +
                "forward 1\n" +
                "forward 4\n" +
                "down 9\n" +
                "up 1\n" +
                "down 8\n" +
                "down 4\n" +
                "down 4\n" +
                "down 2\n" +
                "down 9\n" +
                "forward 7\n" +
                "up 1\n" +
                "down 4\n" +
                "forward 4\n" +
                "down 8\n" +
                "forward 1\n" +
                "forward 8\n" +
                "forward 1\n" +
                "up 7\n" +
                "forward 4\n" +
                "forward 6\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 4\n" +
                "down 1\n" +
                "up 7\n" +
                "up 8\n" +
                "down 9\n" +
                "forward 3\n" +
                "down 3\n" +
                "forward 6\n" +
                "forward 5\n" +
                "up 1\n" +
                "forward 9\n" +
                "up 6\n" +
                "up 1\n" +
                "forward 1\n" +
                "forward 2\n" +
                "forward 7\n" +
                "down 8\n" +
                "up 4\n" +
                "forward 4\n" +
                "down 3\n" +
                "down 3\n" +
                "forward 2\n" +
                "forward 6\n" +
                "down 4\n" +
                "forward 2\n" +
                "forward 8\n" +
                "up 5\n" +
                "down 1\n" +
                "forward 7\n" +
                "up 6\n" +
                "forward 2\n" +
                "down 6\n" +
                "forward 7\n" +
                "down 2\n" +
                "down 9\n" +
                "down 1\n" +
                "up 4\n" +
                "up 8\n" +
                "down 7\n" +
                "up 6\n" +
                "forward 3\n" +
                "forward 4\n" +
                "down 6\n" +
                "forward 5\n" +
                "down 3\n" +
                "up 6\n" +
                "down 3\n" +
                "down 7\n" +
                "forward 7\n" +
                "up 3\n" +
                "down 1\n" +
                "forward 2\n" +
                "up 2\n" +
                "up 6\n" +
                "up 1\n" +
                "up 8\n" +
                "up 3\n" +
                "down 9\n" +
                "down 8\n" +
                "forward 6\n" +
                "up 9\n" +
                "down 1\n" +
                "forward 5\n" +
                "down 4\n" +
                "up 7\n" +
                "down 5\n" +
                "up 1\n" +
                "down 9\n" +
                "down 8\n" +
                "down 2\n" +
                "down 1\n" +
                "up 8\n" +
                "up 7\n" +
                "up 5\n" +
                "down 5\n" +
                "forward 1\n" +
                "forward 6\n" +
                "down 4\n" +
                "down 3\n" +
                "forward 5\n" +
                "forward 5\n" +
                "up 5\n" +
                "down 6\n" +
                "down 6\n" +
                "down 2\n" +
                "down 7\n" +
                "up 1\n" +
                "up 9\n" +
                "up 4\n" +
                "down 7\n" +
                "up 5\n" +
                "forward 5\n" +
                "forward 6\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 6\n" +
                "up 8\n" +
                "forward 8\n" +
                "forward 1\n" +
                "down 6\n" +
                "up 2\n" +
                "forward 8\n" +
                "down 7\n" +
                "down 5\n" +
                "up 1\n" +
                "up 7\n" +
                "up 2\n" +
                "up 3\n" +
                "down 3\n" +
                "forward 1\n" +
                "forward 4\n" +
                "up 8\n" +
                "forward 9\n" +
                "down 1\n" +
                "up 4\n" +
                "forward 3\n" +
                "down 9\n" +
                "down 9\n" +
                "forward 4\n" +
                "down 8\n" +
                "up 2\n" +
                "forward 1\n" +
                "forward 3\n" +
                "up 5\n" +
                "forward 5\n" +
                "up 4\n" +
                "forward 5\n" +
                "forward 6\n" +
                "forward 2\n" +
                "forward 4\n" +
                "up 5\n" +
                "down 7\n" +
                "up 1\n" +
                "forward 7\n" +
                "down 5\n" +
                "forward 5\n" +
                "down 5\n" +
                "up 2\n" +
                "down 3\n" +
                "forward 6\n" +
                "forward 5\n" +
                "up 4\n" +
                "up 5\n" +
                "down 2\n" +
                "forward 2\n" +
                "down 2\n" +
                "down 2\n" +
                "up 8\n" +
                "up 2\n" +
                "down 7\n" +
                "forward 3\n" +
                "down 7\n" +
                "down 7\n" +
                "down 2\n" +
                "up 5\n" +
                "up 5\n" +
                "forward 5\n" +
                "up 5\n" +
                "down 9\n" +
                "down 1\n" +
                "up 7\n" +
                "up 5\n" +
                "forward 5\n" +
                "forward 1\n" +
                "down 7\n" +
                "down 8\n" +
                "down 4\n" +
                "forward 1\n" +
                "down 2\n" +
                "up 9\n" +
                "forward 1\n" +
                "forward 5\n" +
                "forward 8\n" +
                "down 7\n" +
                "down 6\n" +
                "up 2\n" +
                "down 6\n" +
                "forward 4\n" +
                "down 9\n" +
                "down 1\n" +
                "down 9\n" +
                "up 5\n" +
                "up 1\n" +
                "down 9\n" +
                "forward 7\n" +
                "up 4\n" +
                "down 5\n" +
                "up 1\n" +
                "forward 2\n" +
                "forward 2\n" +
                "up 9\n" +
                "forward 8\n" +
                "up 4\n" +
                "up 1\n" +
                "up 6\n" +
                "up 5\n" +
                "down 5\n" +
                "up 4\n" +
                "up 1\n" +
                "forward 9\n" +
                "forward 3\n" +
                "down 4\n" +
                "down 9\n" +
                "down 4\n" +
                "forward 9\n" +
                "down 2\n" +
                "down 1\n" +
                "up 9\n" +
                "up 4\n" +
                "forward 8\n" +
                "forward 9\n" +
                "forward 8\n" +
                "up 4\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 6\n" +
                "down 1\n" +
                "forward 5\n" +
                "forward 4\n" +
                "up 4\n" +
                "forward 4\n" +
                "up 2\n" +
                "forward 7\n" +
                "forward 2\n" +
                "down 2\n" +
                "down 1\n" +
                "up 5\n" +
                "up 7\n" +
                "down 5\n" +
                "down 9\n" +
                "up 1\n" +
                "down 2\n" +
                "forward 4\n" +
                "forward 8\n" +
                "up 1\n" +
                "forward 7\n" +
                "down 7\n" +
                "forward 1\n" +
                "down 2\n" +
                "down 9\n" +
                "forward 7\n" +
                "forward 6\n" +
                "forward 1\n" +
                "forward 6\n" +
                "forward 9\n" +
                "up 8\n" +
                "forward 4\n" +
                "up 6\n" +
                "forward 9\n" +
                "forward 1\n" +
                "forward 7\n" +
                "forward 9\n" +
                "down 9\n" +
                "down 7\n" +
                "down 6\n" +
                "down 2\n" +
                "down 4\n" +
                "forward 9\n" +
                "forward 4\n" +
                "forward 6\n" +
                "forward 1\n" +
                "forward 3\n" +
                "down 2\n" +
                "forward 9\n" +
                "down 9\n" +
                "forward 8\n" +
                "forward 7\n" +
                "up 4\n" +
                "forward 7\n" +
                "forward 8\n" +
                "up 4\n" +
                "down 1\n" +
                "up 3\n" +
                "down 1\n" +
                "down 9\n" +
                "down 5\n" +
                "down 2\n" +
                "down 8\n" +
                "down 3\n" +
                "down 8\n" +
                "forward 2\n" +
                "forward 5\n" +
                "down 5\n" +
                "down 7\n" +
                "forward 4\n" +
                "up 6\n" +
                "forward 5\n" +
                "up 2\n" +
                "up 6\n" +
                "forward 6\n" +
                "down 7\n" +
                "down 8\n" +
                "up 4\n" +
                "up 9\n" +
                "forward 7\n" +
                "down 3\n" +
                "forward 8\n" +
                "forward 6\n" +
                "up 3\n" +
                "up 4\n" +
                "down 1\n" +
                "forward 2\n" +
                "down 9\n" +
                "down 1\n" +
                "down 6\n" +
                "down 5\n" +
                "up 7\n" +
                "forward 7\n" +
                "down 6\n" +
                "down 2\n" +
                "down 5\n" +
                "up 2\n" +
                "forward 7\n" +
                "forward 2\n" +
                "down 6\n" +
                "down 1\n" +
                "forward 4\n" +
                "up 9\n" +
                "down 1\n" +
                "down 7\n" +
                "forward 1";

        String[] array = text.split("[\n: ]");

        String a = array[4];

        //System.out.println(a);

        //System.out.println(Arrays.toString(array));

        int i = 0;
        int num1 = 0;
        int counter = 0;
        int counter2 = 0;
        int aim = 0;

        while (i < 1000) {

            if (Objects.equals(array[num1], "forward")) {
                counter = counter + Integer.parseInt(array[num1 + 1]);
            }
            if (Objects.equals(array[num1], "up")) {
                counter2 = counter2 - Integer.parseInt(array[num1 + 1]);
            }
            if (Objects.equals(array[num1], "down")) {
                counter2 = counter2 + Integer.parseInt(array[num1 + 1]);
            }

            num1 = num1 + 2;
            i++;
        }

        System.out.println(array.length);

        System.out.println(counter);
        System.out.println(counter2);

        System.out.println(counter * counter2);


    }
}
